config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts

  root to: 'posts#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
  	@post =Post.new
  end

  def show
  	@post = Post.find(params[:id])
  end

  def top
  end

  def create
  	post = Post.new(post_params)
  	if post.save
       flash[:notice] = "successfully"
  	   redirect_to post_path(post.id)
    end
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	post = Post.find(params[:id])
  	if post.update(post_params)
  	   flash[:notice] = "successfully"
  	   redirect_to post_path(post.id)
  	end
  end

  def destroy
  	post = Post.find(params[:id])
  	if post.destroy
  	   flash[:notice] = "successfully"
  	   redirect_to posts_path
    end
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>

<div class="field row">
<label for="book_title">Title</label>
<br>
<%= f.text_field :title, class: "book_title" %>
</div>

<div class="field row">
<label for="book_body">Body</label>
<br>
<%= f.text_area :body, class: "book_body" %>
</div>
<%= f.submit "Update Book" %>

<% end %>

<%= link_to 'Show', post_path(@post.id), class: "show_#{@post.id}" %>
|
<%= link_to 'Back', posts_path, class: "back" %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
<% end %>

<h1>Books</h1>
<table>
	<thead>
	    <tr>
		    <th>Title</th>
		    <th>Body</th>
		    <th colspan="3"></th>
	    </tr>
	</thead>

	<tbody>
		<% @posts.each do |post| %>
	        <tr>
	        	<td><%= post.title %></td>
	        	<td><%= post.body %></td>
	        	<td><%= link_to 'Show', post, class: "show_#{post.id}" %></td>
	        	<td><%= link_to 'Edit', edit_post_path(post.id), class: "edit_#{post.id}" %></td>
	        	<td><%= link_to 'Destroy', post, method: :delete, "data-confirm" => "Are you sure?", class: "destroy_#{post.id}" %></td>
	        </tr>
		<% end %>
    </tbody>
</table>

<h2>New book</h2>

<%= form_for(@post) do |f| %>
<div class = "field row">

<%= f.label :title %>
<br>
<%= f.text_field :title, class: "book_title" %>
</div>

<div class = "field row">
<%= f.label :body %>
<br>
<%= f.text_area :body, class: "book_body" %>
</div>

<%= f.submit 'Create Book' %>
<% end %>

app/views/posts/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
<% end %>

<p>
	<strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
	<strong>Body:</strong>
    <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post.id), class: "edit_#{@post.id}" %>
|
<%= link_to 'Back', posts_path, class: "back" %>

app/views/posts/top.html.erb
<h1>
	ようこそ
	<strong>Bookers</strong>
	へ！
</h1>

<p>
	<strong>Bookers</strong>
	では、さまざまな書籍に関するあなたの意見や<br>
	印象を共有し交換することができます
</p>

<%= link_to "start", posts_path %>